---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dragonfly
  namespace: database
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: dragonfly
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from dragonfly operator
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: database
          podSelector:
            matchLabels:
              app.kubernetes.io/name: dragonfly-operator
    # Allow traffic from other dragonfly pods (replication)
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: dragonfly
  egress:
    # Allow access to other dragonfly pods (cluster communication)
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: dragonfly
      ports:
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 9999
