---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teslamate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: teslamate-secret
    template:
      engineVersion: v2
      data:
        # App
        ENCRYPTION_KEY: "{{ .TESLAMATE_ENCRYPTION_KEY }}"
        # Mosquitto
        MQTT_USERNAME: "{{ .MOSQUITTO_USERNAME }}"
        MQTT_PASSWORD: "{{ .MOSQUITTO_PASSWORD }}"
  dataFrom:
    - extract:
        key: mosquitto
    - extract:
        key: teslamate
