---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: teslamate
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  valuesFrom:
    - targetPath: "database"
      valueFrom:
        secretKeyRef:
          name: teslamate-app
          key: dbname
    - targetPath: "user"
      valueFrom:
        secretKeyRef:
          name: teslamate-app
          key: username
    - targetPath: "secureJsonData.password"
      valueFrom:
        secretKeyRef:
          name: teslamate-app
          key: password
  datasource:
    name: TeslaMate
    type: postgres
    access: proxy
    url: "teslamate-r.automation.svc.cluster.local:5432"
    database: ${dbname}
    user: ${username}
    secureJsonData:
      password: ${password}
    jsonData:
      postgresVersion: 1000
      sslmode: disable
