---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teslamate
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: teslamate
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn: []
  values:
    controllers:
      teslamate:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18@sha256:5086f94abc783f1147d7c2a32c01db00ab594820026e4f6a82ac2af3dbde7fc7
              pullPolicy: Always
            env:
              INIT_POSTGRES_HOST: "{{ .Release.Name }}-rw.automation.svc.cluster.local"
              INIT_POSTGRES_USER:
                valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-app"
                      key: username
              INIT_POSTGRES_PASS:
                valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-app"
                      key: password
              INIT_POSTGRES_DBNAME:
                valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-app"
                      key: dbname
              INIT_POSTGRES_SUPER_USER:
                valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-superuser"
                      key: username
              INIT_POSTGRES_SUPER_PASS:
                valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-superuser"
                      key: password
        containers:
          app:
            image:
              repository: teslamate/teslamate
              tag: 3.0.0@sha256:6569026b73bd657455bbec05965d07fa30b6d4d70eaab0bd5b343231c0429167
            env:
              TZ: Europe/Paris
              DISABLE_MQTT: "false"
              MQTT_HOST: mosquitto.automation.svc.cluster.local
              DATABASE_HOST: "{{ .Release.Name }}-rw.automation.svc.cluster.local"
              DATABASE_USER:
                valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-app"
                      key: username
              DATABASE_PASS:
                valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-app"
                      key: password
              DATABASE_NAME:
                valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-app"
                      key: dbname
            envFrom:
              - secretRef:
                  name: teslamate-secret
    service:
      app:
        controller: teslamate
        type: ClusterIP
        ports:
          http:
            port: &port 4000
    route:
      app:
        hostnames:
          - teslamate.oxygn.dev
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    resources:
      requests:
        cpu: 25m
        memory: 256Mi
      limits:
        memory: 384Mi
        cpu: 200m
