---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
spec:
  chartRef:
    kind: OCIRepository
    name: flaresolverr
  interval: 1h
  values:
    controllers:
      flaresolverr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: v3.5.0@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47
            resources:
              requests:
                cpu: 15m
                memory: 256Mi
              limits:
                memory: 1Gi
                cpu: 200m
    service:
      app:
        controller: flaresolverr
        ports:
          http:
            port: 8191
