---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghostfolio
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ghostfolio-secret
    template:
      engineVersion: v2
      data:
        JWT_SECRET_KEY: "{{ .JWT_SECRET_KEY }}"
        ACCESS_TOKEN_SALT: "{{ .ACCESS_TOKEN_SALT }}"
  dataFrom:
    - extract:
        key: ghostfolio
