---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghostfolio
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ghostfolio-secret
    template:
      engineVersion: v2
      data:
        JWT_SECRET_KEY: "{{ .JWT_SECRET_KEY }}"
        ACCESS_TOKEN_SALT: "{{ .ACCESS_TOKEN_SALT }}"
        # DATABASE_URL: "postgresql://{{ .GHOSTFOLIO_DB_USERNAME }}:{{ .GHOSTFOLIO_DB_PASSWORD }}@postgres-rw.database.svc.cluster.local:5432/ghostfolio"
        # Postgres Init
        # INIT_POSTGRES_DBNAME: ghostfolio
        # INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        # INIT_POSTGRES_USER: "{{ .GHOSTFOLIO_DB_USERNAME }}"
        # INIT_POSTGRES_PASS: "{{ .GHOSTFOLIO_DB_PASSWORD }}"
        # INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: ghostfolio
