---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghostfolio
spec:
  chartRef:
    kind: OCIRepository
    name: ghostfolio
  interval: 1h
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn: []
  values:
    controllers:
      ghostfolio:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18@sha256:5086f94abc783f1147d7c2a32c01db00ab594820026e4f6a82ac2af3dbde7fc7
              pullPolicy: Always
            env:
              INIT_POSTGRES_HOST: "{{ .Release.Name }}-rw.self-hosted.svc.cluster.local"
              INIT_POSTGRES_USER:
                valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-app"
                      key: username
              INIT_POSTGRES_PASS:
                valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-app"
                      key: password
              INIT_POSTGRES_DBNAME:
                valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-app"
                      key: dbname
              INIT_POSTGRES_SUPER_USER:
                valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-superuser"
                      key: username
              INIT_POSTGRES_SUPER_PASS:
                valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-superuser"
                      key: password
        containers:
          app:
            image:
              repository: docker.io/ghostfolio/ghostfolio
              tag: 3.6.0@sha256:9baddf839704b833d5c30408fc065403e6af667d8abc3882a9ebae8d9f72af9d
              pullPolicy: IfNotPresent
            env:
              NODE_ENV: production
              TZ: Europe/Paris
              REDIS_HOST: ghostfolio-dragonfly
              REDIS_PORT: "6379"
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-app"
                    key: uri
            envFrom:
              - secretRef:
                  name: ghostfolio-secret
            probes:
              liveness:
                enabled: true
                type: HTTP
                path: /api/v1/health
              readiness:
                enabled: true
                type: HTTP
                path: /api/v1/health
              startup:
                enabled: true
                type: HTTP
                path: /api/v1/health
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
    service:
      app:
        controller: ghostfolio
        type: ClusterIP
        ports:
          http:
            port: &port 3333
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        hostnames:
          - "{{ .Release.Name }}.oxygn.dev"
          - finance.oxygn.dev
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
