---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      # renovate: registryUrl=https://helm.ngc.nvidia.com/nvidia
      chart: gpu-operator
      version: v25.3.0
      sourceRef:
        kind: HelmRepository
        name: gpu-operator
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    disableOpenAPIValidation: true
    remediation:
      retries: 3
  dependsOn:
    - name: nvidia-device-plugin
      namespace: kube-system
  values:
    operator:
      defaultRuntime: "containerd"
      upgradeCRD: true
      cleanupCRD: true
      resources:
        requests:
          cpu: 25m
          memory: 100M
        limits:
          memory: 350M
    dcgmExporter:
      enabled: true
      serviceMonitor:
        enabled: true
    driver:
      enabled: false
    manager:
      env:
        - name: ENABLE_AUTO_DRAIN
          value: "false"
        - name: DRAIN_USE_FORCE
          value: "false"
        - name: DRAIN_POD_SELECTOR_LABEL
          value: "gpu=drain"
        - name: DRAIN_TIMEOUT_SECONDS
          value: "0s"
        - name: DRAIN_DELETE_EMPTYDIR_DATA
          value: "false"
    nfd:
      enabled: false
    psp:
      enabled: false
    toolkit:
      enabled: false
      toolkit:
      env:
        - name: CONTAINERD_RUNTIME_CLASS
          value: nvidia
        - name: CONTAINERD_SET_AS_DEFAULT
          value: "true"
    devicePlugin:
      config:
        create: true
        name: time-slicing-config
        default: any
        data:
          any: |-
            version: v1
            flags:
              migStrategy: none
            sharing:
              timeSlicing:
                renameByDefault: false
                failRequestsGreaterThanOne: false
                resources:
                  - name: nvidia.com/gpu
                    replicas: 4
