---
apiVersion: v1
kind: Service
metadata:
  name: &app minio
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName
  externalName: funkstation.internal
  # type: ClusterIP
  # clusterIP: None
  ports:
    - name: http-minio-console
      port: &port-console 9001
      protocol: TCP
      targetPort: *port-console
    - name: http-minio-api
      port: &port-api 9000
      protocol: TCP
      targetPort: *port-api
---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio-http
spec:
  hostnames: ["minio.oxygn.dev"]
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: minio
          namespace: network
          port: 9001
      matches:
        - path:
            type: PathPrefix
            value: /
---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio-s3
spec:
  hostnames: ["s3.oxygn.dev"]
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: minio
          namespace: network
          port: 9000
      matches:
        - path:
            type: PathPrefix
            value: /
