---
apiVersion: v1
kind: Service
metadata:
  name: &app funkstation
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName
  externalName: funkstation.internal
  # type: ClusterIP
  # clusterIP: None
  ports:
    - name: http-syno
      port: &port 5000
      protocol: TCP
      targetPort: *port
---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: funkstation
spec:
  hostnames: ["funkstation.oxygn.dev"]
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: funkstation
          namespace: network
          port: 5000
      matches:
        - path:
            type: PathPrefix
            value: /
