---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus
  namespace: observability
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from all namespaces (metrics collection)
    - from:
        - namespaceSelector: {}

  egress:
    # Allow scrape from all namespaces (metrics collection)
    - to:
        - namespaceSelector: {}
