---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: pve-exporter
spec:
  staticConfigs:
    - targets:
      - pve.internal:8006  # Proxmox VE node.
      - pve2.internal:8006  # Proxmox VE node.
  metricsPath: /pve
  params:
    module: ["default"]
    cluster: ["1"]
    node: ["1"]
  relabelings:
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - sourceLabels: [__param_target]
      targetLabel: instance
    - targetLabel: __address__
      replacement: pve-exporter.observability:9221  # PVE exporter.
---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: minio
spec:
  metricsPath: /minio/v2/metrics/cluster
  scheme: HTTP
  staticConfigs:
    - targets: ['minio.network:9000']
