---
# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
extends: default
rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  line-length:
    max: 150
    level: warning
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
