---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./mainclaw.yaml
  - ./devclaw.yaml
  - ./opencode.yaml
  - ./pr-review.yaml
  - ./memini.yaml
  - ./lightrag.yaml
