---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${APP}-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ${OIDC_ROUTE_NAME}
  oidc:
    provider:
      issuer: https://authentik.${DOMAIN:=oxygn.dev}/application/o/${APP}/
    clientIDRef:
      group: ""
      kind: Secret
      name: ${APP}-oidc
    clientSecret:
      group: ""
      kind: Secret
      name: ${APP}-oidc
    redirectURL: https://${SUBDOMAIN}.${DOMAIN:=oxygn.dev}${OIDC_CALLBACK:=/oauth2/callback}
    logoutPath: /logout
    scopes: ["openid", "email", "profile"]
