---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: neo4j
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: neo4j-secret
    template:
      data:
        NEO4J_AUTH: "neo4j/{{ .NEO4J_PASSWORD }}"
  dataFrom:
    - extract:
        key: lightrag
