---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neo4j
spec:
  interval: 1h
  chart:
    spec:
      chart: neo4j
      version: 2026.5.0
      sourceRef:
        kind: HelmRepository
        name: neo4j
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    disableLookups: true
    neo4j:
      name: neo4j
      edition: community
      passwordFromSecret: neo4j-secret
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: 2000m
          memory: 3Gi
    volumes:
      data:
        mode: volume
        volume:
          persistentVolumeClaim:
            claimName: neo4j
    services:
      neo4j:
        enabled: false
      admin:
        enabled: true
        spec:
          type: ClusterIP
    config:
      server.config.strict_validation.enabled: "false"
      server.memory.heap.initial_size: "512m"
      server.memory.heap.max_size: "1G"
      server.memory.pagecache.size: "1G"
      server.metrics.prometheus.enabled: "true"
      server.metrics.prometheus.endpoint: "0.0.0.0:2004"
    serviceMonitor:
      enabled: true
      selector:
        matchLabels:
          helm.neo4j.com/service: admin
      port: tcp-prometheus
      interval: 30s
      path: /metrics
    podSpec:
      annotations:
        reloader.stakater.com/auto: "true"
