---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: konflate
  data:
    - secretKey: KONFLATE_APP_PRIVATE_KEY
      remoteRef:
        key: github
        property: GITHUB_APP_PRIVATE_KEY
    - secretKey: KONFLATE_WEBHOOK_SECRET
      remoteRef:
        key: konflate
        property: KONFLATE_WEBHOOK_SECRET
