---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: teslamate
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: teslamate
  components:
    - ../../../../components/postgres
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  dependsOn:
    - name: onepassword
      namespace: external-secrets
    - name: mosquitto
      namespace: automation
  interval: 1h
  path: ./kubernetes/apps/automation/teslamate/app
  postBuild:
    substitute:
      APP: teslamate
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: automation
  wait: false
