---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./litellmproxy.yaml
  - ./servicemonitor.yaml
  - ./virtualkeys
  - ./models
  - ./dashboard
  - ./grafanadashboard.yaml
  - ./prometheusrule.yaml
configMapGenerator:
  - name: litellm-configmap
    files:
      - session_hook.py=./resources/session_hook.py
generatorOptions:
  disableNameSuffixHash: true
