---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lightrag
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: lightrag-secret
    template:
      engineVersion: v2
      data:
        LLM_BINDING_API_KEY: "{{ .LITELLM_LIGHTRAG_KEY }}"
        EMBEDDING_BINDING_API_KEY: "{{ .LITELLM_LIGHTRAG_KEY }}"
        LIGHTRAG_API_KEY: "{{ .LIGHTRAG_API_KEY }}"
  data:
    - secretKey: LITELLM_LIGHTRAG_KEY
      remoteRef:
        key: litellm
        property: key-lightrag
  dataFrom:
    - extract:
        key: lightrag
