---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-ops-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: home-ops-runner-secret
    template:
      data:
        github_app_id: '{{ .GITHUB_APP_ID }}'
        github_app_installation_id: '{{ .GITHUB_APP_INSTALLATION_ID }}'
        github_app_private_key: '{{ .GITHUB_APP_PRIVATE_KEY }}'
        # github_app_secret_token: '{{ .GITHUB_APP_SECRET_TOKEN }}'
  dataFrom:
    - extract:
        key: actions-runner-controller
