---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secret
    template:
      data:
        AUTHENTIK_SECRET_KEY: "{{ .secret_key }}"
        AUTHENTIK__BOOTSTRAP_PASSWORD: "{{ .bootstrap_password }}"
  dataFrom:
    - extract:
        key: authentik
