---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secret
    template:
      data:
        AUTHENTIK_SECRET_KEY: "{{ .secret_key }}"
        AUTHENTIK__BOOTSTRAP_PASSWORD: "{{ .bootstrap_password }}"
        OPENCODE_CLIENT_ID: "{{ .opencode_client_id }}"
        OPENCODE_CLIENT_SECRET: "{{ .opencode_client_secret }}"
  dataFrom:
    - extract:
        key: authentik
  data:
    - secretKey: opencode_client_id
      remoteRef:
        key: opencode
        property: OPENCODE_CLIENT_ID
    - secretKey: opencode_client_secret
      remoteRef:
        key: opencode
        property: OPENCODE_CLIENT_SECRET
