---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  chartRef:
    kind: OCIRepository
    name: authentik
  interval: 1h
  dependsOn: []
  values:
    blueprints:
      configMaps:
        - authentik-blueprint
        - mainclaw-blueprint
        - opencode-blueprint
    global:
      podAnnotations:
        reloader.stakater.com/auto: "true"
      deploymentStrategy:
        type: RollingUpdate
      env:
        - name: AUTHENTIK_POSTGRESQL__NAME
          value: *app
        - name: AUTHENTIK_POSTGRESQL__HOST
          value: authentik-rw.security.svc
        - name: AUTHENTIK_POSTGRESQL__USER
          value: *app
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-app
              key: password
        - name: AUTHENTIK_POSTGRESQL__SSLMODE
          value: require
        - name: AUTHENTIK_REDIS__HOST
          value: authentik-dragonfly
      envFrom:
        - secretRef:
            name: authentik-secret
    server:
      resources:
        requests:
          cpu: 200m
        limits:
          memory: 1Gi
      metrics:
        prometheus:
          serviceMonitor:
            enabled: true
      route:
        main:
          enabled: true
          hostnames: ["authentik.oxygn.dev"]
          parentRefs:
            - name: envoy-external
              namespace: network
    worker:
      resources:
        requests:
          cpu: 200m
        limits:
          memory: 1Gi
