---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-issuer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-issuer-secret
    template:
      data:
        CLOUDFLARE_DNS_API_TOKEN: "{{ .CLOUDFLARE_DNS_API_TOKEN }}"
  dataFrom:
    - extract:
        key: cloudflare
