---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app forgejo
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *app
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: forgejo
        property: username
    - secretKey: password
      remoteRef:
        key: forgejo
        property: password
