---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: &app forgejo
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: *app
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: forgejo
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: forgejo
          property: password
