---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: VirtualMCPServer
metadata:
  name: mcp-gateway-internal
spec:
  groupRef:
    name: mcp-tools
  config:
    aggregation:
      conflictResolution: prefix
      conflictResolutionConfig:
        prefixFormat: "{workload}_"
  # embeddingServerRef:
  #   name: mcp-tools-embedding
  telemetryConfigRef:
    name: prometheus
  incomingAuth:
    type: anonymous
  outgoingAuth:
    source: discovered
  # sessionStorage:
  #   address: toolhive-dragonfly.ai.svc.cluster.local:6379
  #   keyPrefix: "mcp-gateway-internal:"
  #   provider: redis
