---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: komga
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: komga
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      komga:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: gotson/komga
              tag: "1.26.1@sha256:e109902ebebb8a05f633f48d84a2ac7bb1334bf0f6fbc17262a333082c7de44d"
            env:
              TZ: Europe/Paris
              SERVER_PORT: &port 80
              KOMGA_CONFIGDIR: /config
              LOGGING_FILE_NAME: /dev/stdout
            resources:
              requests:
                cpu: 15m
                memory: 640Mi
              limits:
                memory: 1024Mi
                cpu: 200m
    service:
      app:
        controller: komga
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.oxygn.dev"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: komga

      media:
        type: nfs
        server: funkstation.internal
        path: /volume2/Media/Comics
        globalMounts:
          - path: /media/comics
            readOnly: true

      books:
        type: nfs
        server: funkstation.internal
        path: /volume2/Media/Books/readarr
        globalMounts:
          - path: /media/books
            readOnly: true
