---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tuppr-notifications
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tuppr-notifications
    template:
      engineVersion: v2
      data:
        url: "discord://{{ .WEBHOOK_ID }}/{{ .WEBHOOK_TOKEN }}"
  dataFrom:
    - extract:
        key: tuppr
