---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./devclaw/ks.yaml
  - ./embeddings/ks.yaml
  - ./headroom/ks.yaml
  - ./lightrag/ks.yaml
  - ./litellm/ks.yaml
  - ./llmkube/ks.yaml
  - ./mainclaw/ks.yaml
  - ./memini/ks.yaml
  - ./searxng/ks.yaml
  - ./toolhive/ks.yaml
