---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./backube.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./descheduler.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./gpu-operator.yaml
  - ./grafana.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./nvidia-device-plugin.yaml
  - ./ollama.yaml
  - ./open-webui.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
  - ./wiremind.yaml
