---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: silence-operator
  namespace: observability
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: silence-operator
  policyTypes:
    - Ingress
    - Egress
  egress:
    # Allow access to AlertManager
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
          podSelector:
            matchLabels:
              app.kubernetes.io/name: alertmanager
      ports:
        - protocol: TCP
          port: 9093
    # Allow access to Prometheus
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
          podSelector:
            matchLabels: