---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: unifi-dns
  namespace: network
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: unifi-dns
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from kube-system (DNS responses)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
  egress:
    # Allow access to Gateway API resources
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: network
    # Allow access to Unifi controller
    - to:
        - ipBlock:
            cidr: 10.10.50.0/24
      ports:
        - protocol: TCP
          port: 443