---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
spec:
  interval: 30m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.36
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    adminUser:
      create: true
      createSecret: false
      username: admin
    image:
      tag: "v0.39.0-rc.2" #TODO : remove when chart will be updated
    networkPolicy:
      create: false
    metrics:
      enabled: true
    rbac:
      create: true
      additionalRules:
        - apiGroups: [ "infra.contrib.fluxcd.io" ]
          resources: [ "terraforms" ]
          verbs: [ "get", "list", "patch" ]
    podAnnotations:
      secret.reloader.stakater.com/reload: cluster-user-auth
