---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: go-glm-5.3
spec:
  modelName: go-glm-5.3
  proxyRef: litellm
  params:
    model: openai/glm-5.3
    apiBase: https://opencode.ai/zen/go/v1
    apiKey: os.environ/OPENCODE_API_KEY
  info:
    mode: chat
    maxInputTokens: 1000000
    maxOutputTokens: 131072
    supportsFunctionCalling: true
    supportsVision: false
    supportsPromptCaching: true
