---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: go-glm-5.3-flash
spec:
  modelName: go-glm-5.3-flash
  proxyRef: litellm
  params:
    model: openai/glm-5.3-flash
    apiBase: https://opencode.ai/zen/go/v1
    apiKey: os.environ/OPENCODE_API_KEY
  info:
    mode: chat
    maxInputTokens: 1000000
    maxOutputTokens: 32768
    supportsFunctionCalling: true
    supportsVision: true
    supportsPromptCaching: true
