---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
  dataFrom:
  - extract:
      key: sonarr
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
  dataFrom:
  - extract:
      key: radarr
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
  dataFrom:
  - extract:
      key: prowlarr
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com//external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-github
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        token: "{{ .GH_TOKEN }}"
  dataFrom:
    - extract:
        key: devclaw
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        HOMEASSISTANT_TOKEN: "{{ .HASS_OPENCLAW_TOKEN }}"
  dataFrom:
    - extract:
        key: home-assistant
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-lightrag
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        LIGHTRAG_API_KEY: "{{ .LIGHTRAG_API_KEY }}"
  dataFrom:
    - extract:
        key: lightrag
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-seerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        SEERR_API_KEY: "{{ .SEERR_API_KEY }}"
  dataFrom:
    - extract:
        key: seerr
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-todoist
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        TODOIST_API_KEY: "{{ .TODOIST_API_KEY }}"
  dataFrom:
    - extract:
        key: todoist
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-unifi-network-username
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        UNIFI_NETWORK_USERNAME: "{{ .UNIFI_PUCHU_USERNAME }}"
  dataFrom:
    - extract:
        key: unifi
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-unifi-network-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        UNIFI_NETWORK_PASSWORD: "{{ .UNIFI_PUCHU_PASSWORD }}"
  dataFrom:
    - extract:
        key: unifi
