---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: devclaw
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: devclaw-secret
    template:
      engineVersion: v2
      data:
        ## Gateway token for authentication
        OPENCLAW_GATEWAY_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
        ## Discord
        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        DISCORD_GUILD_ID: "{{ .DISCORD_GUILD_ID }}"
        DISCORD_DEVOPS_CHANNEL_ID: "{{ .DISCORD_DEVOPS_CHANNEL_ID }}"
        DISCORD_MATT_USER_ID: "{{ .DISCORD_MATT_USER_ID }}"
        ## Github
        GH_TOKEN: "{{ .GH_TOKEN }}"
        ## Litellm
        LITELLM_API_KEY: "{{ .LITELLM_MASTER_KEY }}"
  dataFrom:
    - extract:
        key: devclaw
    - extract:
        key: litellm
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: devclaw-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: devclaw-config
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: devclaw-configmap
            items:
              - key: openclaw.json
  dataFrom:
    - extract:
        key: devclaw
