---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: embeddings
spec:
  chartRef:
    kind: OCIRepository
    name: embeddings
  interval: 1h
  values:
    controllers:
      embeddings:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/huggingface/text-embeddings-inference
              tag: cpu-1.9.3
            args:
              - --model-id
              - BAAI/bge-m3
            env:
              TZ: Europe/Paris
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 80
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 80
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 80
                  initialDelaySeconds: 600
                  periodSeconds: 10
                  failureThreshold: 30
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      data:
        existingClaim: embeddings
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    service:
      app:
        ports:
          http:
            port: 80
