---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plane-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .SECRET_KEY }}"
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: plane
        property: SECRET_KEY
