---
originRequest:
  originServerName: external.oxygn.dev

ingress:
  - hostname: oxygn.dev
    service: &svc https://envoy-network-external.network.svc.cluster.local
  - hostname: "*.oxygn.dev"
    service: *svc
  - service: http_status:404
