---
originRequest:
  originServerName: external.oxygn.dev

ingress:
  - hostname: oxygn.dev
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.oxygn.dev"
    service: *svc
  - service: http_status:404
