---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plex-secret
    template:
      engineVersion: v2
      data:
        # App
        PLEX_CLAIM: "{{ .PLEX_CLAIM }}"
  dataFrom:
    - extract:
        key: plex
