[env]
_.file = ["{{config_root}}/.secrets.env"]
FLATE_PATH = '{{config_root}}/kubernetes/flux/cluster'
KUBECONFIG = '{{config_root}}/kubeconfig'
MINIJINJA_CONFIG_FILE = '{{config_root}}/.minijinja.toml'
TALOSCONFIG = '{{config_root}}/talosconfig'
JUST_UNSTABLE = "1"

[settings]
experimental = true

[tools]
# Runtimes
node = "24.18.0"
python = "3.14.6"
uv = "0.11.25"
go = "1.26.4"
gum = "0.17.0"

# Mise
"just" = "1.54.0"
"yq" = "4.53.3"
"jq" = "1.8.2"
"rg" = "15.1.0"
"gh" = "2.95.0"

# 1Password
"vals" = "0.44.2"

# Flux Stuff
"aqua:fluxcd/flux2" = "2.8.8"
"github:home-operations/flate" = "0.4.10"

# Kubectl + Plugins
"aqua:kubernetes/kubectl" = "1.32.3"
"aqua:yannh/kubeconform" = "0.8.0"

# Misc K8S Tools
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:helm/helm" = "4.2.2"
"aqua:helmfile/helmfile" = "1.6.0"

# Talos Stuff
"talosctl" = "1.13.5"
"aqua:budimanjojo/talhelper" = "3.1.12"

# Misc Tools
"aqua:cert-manager/cmctl" = "2.5.0"
"aqua:cloudflare/cloudflared" = "2026.6.1"
"asdf:carnei-ro/asdf-cilium-cli" = "0.18.2"
"aqua:cilium/hubble" = "1.19.4"

# Security
"aqua:kubescape/kubescape" = "4.0.9"

# Linters
"pipx:yamllint" = "1.38.0"
