---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app prowlarr
  namespace: &namespace nzb
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/guarded
    - ../../../../components/keda/nfs-scaler
    - ../../../../components/volsync
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    - name: cloudnative-pg-cluster
      namespace: database
    - name: volsync
      namespace: volsync-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: keda
      namespace: observability
  interval: 30m
  path: ./kubernetes/apps/nzb/prowlarr/app
  postBuild:
    substitute:
      APP: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
