---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kguardian-gemini
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kguardian-gemini-secret
    template:
      data:
        API_KEY: "{{ .GEMINI_API_KEY }}"
  dataFrom:
    - extract:
        key: openclaw
