---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: snmp-exporter
  namespace: observability
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: snmp-exporter
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow Prometheus to scrape
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
          podSelector:
            matchLabels: