---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mosquitto
  namespace: automation
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from teslamate (same namespace)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: automation
          podSelector:
            matchLabels:
              app.kubernetes.io/name: teslamate
    # Allow traffic within automation namespace for other clients
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: automation
  egress: {}
