---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oxygn-dev
spec:
  secretName: oxygn-dev-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: oxygn.dev
  dnsNames: ["oxygn.dev", "*.oxygn.dev"]
