---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-dashboard
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rook-ceph-dashboard-password
    template:
      engineVersion: v2
      data:
        # App
        password: "{{ .ROOK_CEPH_DASHBOARD_PASSWORD }}"
  dataFrom:
    - extract:
        key: rook-ceph
