---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: volsync
  namespace: volsync-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: volsync-perfectra1n
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from ingress (envoy)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: network
    # Allow Prometheus to scrape
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
          podSelector:
            matchLabels: