---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mainclaw
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mainclaw-secret
    template:
      engineVersion: v2
      data:
        ## Gateway token for authentication
        OPENCLAW_GATEWAY_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
        ## Discord
        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        DISCORD_GUILD_ID: "{{ .DISCORD_GUILD_ID }}"
        DISCORD_CLAW_CHANNEL_ID: "{{ .DISCORD_CLAW_CHANNEL_ID }}"
        DISCORD_FAMILY_CHANNEL_ID: "{{ .DISCORD_FAMILY_CHANNEL_ID }}"
        DISCORD_COACH_CHANNEL_ID: "{{ .DISCORD_COACH_CHANNEL_ID }}"
        DISCORD_FINANCE_CHANNEL_ID: "{{ .DISCORD_FINANCE_CHANNEL_ID }}"
        DISCORD_SHOPPING_CHANNEL_ID: "{{ .DISCORD_SHOPPING_CHANNEL_ID }}"
        DISCORD_NOVA_CHANNEL_ID: "{{ .DISCORD_NOVA_CHANNEL_ID }}"
        DISCORD_MEDIA_CHANNEL_ID: "{{ .DISCORD_MEDIA_CHANNEL_ID }}"
        DISCORD_LYCOS_CHANNEL_ID: "{{ .DISCORD_LYCOS_CHANNEL_ID }}"
        DISCORD_CLAW_PROJECT_FORUM: "{{ .DISCORD_CLAW_PROJECT_FORUM }}"
        DISCORD_NOVA_PROJECT_FORUM: "{{ .DISCORD_NOVA_PROJECT_FORUM }}"
        DISCORD_MATT_USER_ID: "{{ .DISCORD_MATT_USER_ID }}"
        DISCORD_AGNES_USER_ID: "{{ .DISCORD_AGNES_USER_ID }}"
        ## Litellm
        LITELLM_API_KEY: "{{ .LITELLM_MASTER_KEY }}"
        ## Memini
        MEMINI_API_KEY: "{{ .MEMINI_API_KEY }}"
        ## 1password
        OP_SERVICE_ACCOUNT_TOKEN: "{{ .OP_SERVICE_ACCOUNT_TOKEN }}"

  dataFrom:
    - extract:
        key: mainclaw
    - extract:
        key: litellm
    - extract:
        key: memini
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mainclaw-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mainclaw-config
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: mainclaw-configmap
            items:
              - key: openclaw.json
  dataFrom:
    - extract:
        key: mainclaw
