---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app opencode
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 15m
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      opencode:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init:
            image:
              repository: docker.io/library/alpine
              tag: "3.24"
            command:
              - sh
              - -c
              - cp /kopiaignore/.kopiaignore /home/opencode/.kopiaignore
        containers:
          app:
            image:
              repository: ghcr.io/joryirving/opencode
              tag: 1.18.30@sha256:58dc035ef0d0ca1cbab1657f23a19132195f410a51d1642494f71a64e7c193cf
            command: ["/etc/opencode/entrypoint.sh"]
            env:
              HOME: &homepath /home/opencode
              OPENCODE_CONFIG: /etc/opencode/opencode.json
              TZ: Europe/Paris
            envFrom:
              - secretRef:
                  name: *app
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 4096
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *port
                  initialDelaySeconds: 15
                  periodSeconds: 15
                  failureThreshold: 6
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 8Gi
    service:
      app:
        forceRename: opencode-server
        ports:
          http:
            port: *port
    persistence:
      home:
        existingClaim: *app
        globalMounts:
          - path: *homepath
      kopiaignore:
        type: configMap
        name: opencode-kopiaignore
        globalMounts:
          - path: /kopiaignore
      config:
        type: configMap
        name: opencode-config
        defaultMode: 0755
        globalMounts:
          - path: /etc/opencode
