---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: pve
  namespace: network
  labels:
    kubernetes.io/service-name: pve
addressType: FQDN
endpoints:
  - addresses:
      - pve.internal
    conditions:
      ready: true
ports:
  - name: https
    port: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: &app pve
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ports:
    - name: https-pve
      port: &port 8006
      protocol: TCP
      targetPort: *port
---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pve
spec:
  hostnames: ["pve.oxygn.dev"]
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: pve
          namespace: network
          port: 8006
      matches:
        - path:
            type: PathPrefix
            value: /
