---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: openebs
  namespace: openebs-system
spec:
  podSelector:
    matchLabels:
      name: openebs-localpv-provisioner
  policyTypes:
    - Ingress
    - Egress
  egress:
    # Allow access to all namespaces for storage operations
    - to:
        - namespaceSelector: {}