---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oikos
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oikos
    template:
      data:
        SESSION_SECRET: "{{ .SESSION_SECRET }}"
        DB_ENCRYPTION_KEY: "{{ .DB_ENCRYPTION_KEY }}"
        GOOGLE_CLIENT_ID: "{{ .GOOGLE_CLIENT_ID }}"
        GOOGLE_CLIENT_SECRET: "{{ .GOOGLE_CLIENT_SECRET }}"
        GOOGLE_REDIRECT_URI: "{{ .GOOGLE_REDIRECT_URI }}"
  dataFrom:
    - extract:
        key: oikos
